// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOw7wvGYaAyIdnW1TgQ190eakBnscWJZU',
    appId: '1:104554069846:web:68c38b91a5facf9ea1e0f7',
    messagingSenderId: '104554069846',
    projectId: 'chatapp-bfe4c',
    authDomain: 'chatapp-bfe4c.firebaseapp.com',
    storageBucket: 'chatapp-bfe4c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDI43iaZ_CgtL8nhBbAXDebIQikOm8Y5xc',
    appId: '1:104554069846:android:e240f89c3b2d8a3ea1e0f7',
    messagingSenderId: '104554069846',
    projectId: 'chatapp-bfe4c',
    storageBucket: 'chatapp-bfe4c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuAgzsdlvR5bXXcItvUMk31NY0BOYVDzw',
    appId: '1:104554069846:ios:2f3610c0d1f20c32a1e0f7',
    messagingSenderId: '104554069846',
    projectId: 'chatapp-bfe4c',
    storageBucket: 'chatapp-bfe4c.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuAgzsdlvR5bXXcItvUMk31NY0BOYVDzw',
    appId: '1:104554069846:ios:2f3610c0d1f20c32a1e0f7',
    messagingSenderId: '104554069846',
    projectId: 'chatapp-bfe4c',
    storageBucket: 'chatapp-bfe4c.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOw7wvGYaAyIdnW1TgQ190eakBnscWJZU',
    appId: '1:104554069846:web:8a1b37226b236140a1e0f7',
    messagingSenderId: '104554069846',
    projectId: 'chatapp-bfe4c',
    authDomain: 'chatapp-bfe4c.firebaseapp.com',
    storageBucket: 'chatapp-bfe4c.firebasestorage.app',
  );
}
